In [1]:
import pandas as pd

In [2]:
pandas_version = pd.__version__
print(f"Pandas version: {pandas_version}")

Pandas version: 2.3.2


In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [5]:
records = len(df)
print(f"Number of records using len(): {records}")

Number of records using len(): 9704


In [6]:
fuel_type = len(df.fuel_type.unique())
print(f"Number of unique fuel types: {fuel_type}")

Number of unique fuel types: 2


In [7]:
coulmns_with_missing_values = len(df.columns[df.isnull().any()].tolist())
print(f"Columns with missing values: {coulmns_with_missing_values}")

Columns with missing values: 4


In [9]:
fuel_efficiency_asian_max = df[df.origin == 'Asia'].fuel_efficiency_mpg.max()
print(f"Maximum fuel efficiency for Asian cars: {fuel_efficiency_asian_max}")

Maximum fuel efficiency for Asian cars: 23.759122836520497


In [10]:
median_horsepower = df.horsepower.median()
print(f"Median horsepower: {median_horsepower}")

Median horsepower: 149.0


In [11]:
frequent_horsepower = df.horsepower.mode()[0]
print(f"Most frequent horsepower: {frequent_horsepower}")

Most frequent horsepower: 152.0


In [15]:
df['horsepower'] = df['horsepower'].fillna(frequent_horsepower)
print(df['horsepower'].isnull().sum())  # Should print 0 if all NaNs are filled

0


In [16]:
median_horsepower = df.horsepower.median()
print(f"Median horsepower: {median_horsepower}")

Median horsepower: 152.0


In [7]:
cars_from_asia = df[df.origin == 'Asia']
cars_from_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [10]:
subset_colums = df[['vehicle_weight', 'model_year']]
print(subset_colums)

      vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]


In [11]:
first_seven_values = df[['vehicle_weight', 'model_year']].head(7)
print(first_seven_values)   

   vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012


In [12]:
x = df[['vehicle_weight', 'model_year']].head(7)
print(x)  # Should print the same as first_seven_values

   vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012


In [27]:
X = x.values
print(X)

[[3413.43375861 2003.        ]
 [3149.66493422 2007.        ]
 [3079.03899737 2018.        ]
 [2542.39240183 2009.        ]
 [3460.87098999 2009.        ]
 [2484.88398604 2008.        ]
 [3006.54228722 2012.        ]]


In [28]:
X_transposed = X.T
X_transposed

array([[3413.43375861, 3149.66493422, 3079.03899737, 2542.39240183,
        3460.87098999, 2484.88398604, 3006.54228722],
       [2003.        , 2007.        , 2018.        , 2009.        ,
        2009.        , 2008.        , 2012.        ]])

In [29]:
matrix_matrix_product = x.dot(X_transposed)
matrix_matrix_product

0             1             2             3             4  \
0  1.566354e+07  1.477119e+07  1.455215e+07  1.270232e+07  1.583748e+07   
1  1.477119e+07  1.394844e+07  1.374807e+07  1.203975e+07  1.493265e+07   
2  1.455215e+07  1.374807e+07  1.355281e+07  1.188229e+07  1.471032e+07   
3  1.270232e+07  1.203975e+07  1.188229e+07  1.049984e+07  1.283497e+07   
4  1.583748e+07  1.493265e+07  1.471032e+07  1.283497e+07  1.601371e+07   
5  1.250401e+07  1.185661e+07  1.170320e+07  1.035162e+07  1.263393e+07   
6  1.429267e+07  1.350768e+07  1.331748e+07  1.168592e+07  1.444736e+07   

              5             6  
0  1.250401e+07  1.429267e+07  
1  1.185661e+07  1.350768e+07  
2  1.170320e+07  1.331748e+07  
3  1.035162e+07  1.168592e+07  
4  1.263393e+07  1.444736e+07  
5  1.020671e+07  1.151100e+07  
6  1.151100e+07  1.308744e+07

In [30]:
import numpy as np
inverse_matrix = np.linalg.pinv(matrix_matrix_product)
inverse_matrix

array([[ 5.79803612e-07,  1.63276694e-07,  2.85036821e-08,
        -7.78811789e-07,  6.38982520e-07, -8.65242574e-07,
        -6.93578766e-08],
       [ 1.63276694e-07,  4.67819404e-08,  9.09385640e-09,
        -2.16706425e-07,  1.79831574e-07, -2.40880509e-07,
        -1.82800406e-08],
       [ 2.85036821e-08,  9.09385640e-09,  2.82071758e-09,
        -3.48119347e-08,  3.12662297e-08, -3.88408943e-08,
        -1.74468566e-09],
       [-7.78811789e-07, -2.16706425e-07, -3.48119347e-08,
         1.05463440e-06, -8.58662159e-07,  1.17126990e-06,
         9.72402122e-08],
       [ 6.38982520e-07,  1.79831574e-07,  3.12662297e-08,
        -8.58662159e-07,  7.04216822e-07, -9.53937438e-07,
        -7.66091665e-08],
       [-8.65242574e-07, -2.40880509e-07, -3.88408943e-08,
         1.17126990e-06, -9.53937438e-07,  1.30082368e-06,
         1.07837454e-07],
       [-6.93578766e-08, -1.82800406e-08, -1.74468566e-09,
         9.72402122e-08, -7.66091665e-08,  1.07837454e-07,
         1.0249855

In [31]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]


In [36]:
w = (X_transposed).dot(inverse_matrix).dot(y)
print(w)
sum_w = w.sum()
print(sum_w)

[0.07099685 0.41931263]
0.4903094879707458
